# Generated by Django 6.1.1 on 2026-09-20 04:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0002_seed_vehicle_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPlatformRollup',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True, unique=True)),
                ('rides_requested', models.PositiveIntegerField(default=0)),
                ('rides_completed', models.PositiveIntegerField(default=0)),
                ('rides_cancelled', models.PositiveIntegerField(default=0)),
                ('rides_no_driver_found', models.PositiveIntegerField(default=0)),
                ('active_drivers', models.PositiveIntegerField(default=0)),
                ('offers_sent', models.PositiveIntegerField(default=0)),
                ('offers_accepted', models.PositiveIntegerField(default=0)),
                ('offers_expired', models.PositiveIntegerField(default=0)),
                ('offers_declined', models.PositiveIntegerField(default=0)),
                ('payment_failures', models.PositiveIntegerField(default=0)),
                ('rides_with_earning', models.PositiveIntegerField(default=0)),
                ('gross_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('platform_commission', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('driver_earnings', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('average_fare', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'analytics_daily_platform_rollup',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='DailyVehicleTypeRollup',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('ride_count', models.PositiveIntegerField(default=0)),
                ('gross_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('platform_commission', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('rollup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_type_breakdowns', to='analytics.dailyplatformrollup')),
                ('vehicle_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_revenue_rollups', to='vehicles.vehicletype')),
            ],
            options={
                'db_table': 'analytics_daily_vehicle_type_rollup',
                'ordering': ['-date', '-gross_revenue'],
                'constraints': [models.UniqueConstraint(fields=('date', 'vehicle_type'), name='uniq_vehicle_type_rollup_per_day')],
            },
        ),
    ]
