# Generated by Django 6.1.1 on 2026-09-15 09:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rides', '0002_ride_estimated_distance_km_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('guest_phone_number', models.CharField(blank=True, max_length=32)),
                ('channel', models.CharField(choices=[('IN_APP', 'In-App'), ('EMAIL', 'Email'), ('SMS', 'SMS'), ('PUSH', 'Push')], max_length=10)),
                ('event_type', models.CharField(choices=[('RIDE_REQUESTED', 'Ride Requested'), ('RIDE_DRIVER_ASSIGNED', 'Driver Assigned'), ('RIDE_DRIVER_ARRIVING', 'Driver Arriving'), ('RIDE_DRIVER_ARRIVED', 'Driver Arrived'), ('RIDE_STARTED', 'Ride Started'), ('RIDE_COMPLETED', 'Ride Completed'), ('PAYMENT_COMPLETED', 'Payment Completed'), ('PAYMENT_FAILED', 'Payment Failed'), ('DRIVER_APPROVED', 'Driver Approved'), ('DRIVER_SUSPENDED', 'Driver Suspended'), ('PAYOUT_COMPLETED', 'Payout Completed')], db_index=True, max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('body', models.CharField(max_length=1000)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('failure_reason', models.CharField(blank=True, max_length=255)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('idempotency_key', models.CharField(max_length=150, unique=True)),
                ('recipient_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('ride', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='rides.ride')),
            ],
            options={
                'db_table': 'notifications_notification',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient_user', 'status'], name='notificatio_recipie_3f887c_idx')],
            },
        ),
    ]
