# Generated by Django 6.1.1 on 2026-09-09 03:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rides', '0002_ride_estimated_distance_km_and_more'),
        ('vehicles', '0002_seed_vehicle_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fare',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fare_type', models.CharField(choices=[('ESTIMATE', 'Estimate'), ('FINAL', 'Final'), ('CANCELLATION', 'Cancellation Fee')], max_length=20)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('distance_km', models.DecimalField(decimal_places=2, max_digits=7)),
                ('duration_minutes', models.DecimalField(decimal_places=1, max_digits=6)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fares', to='rides.ride')),
            ],
            options={
                'db_table': 'pricing_fare',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FareLineItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_type', models.CharField(choices=[('BASE_FARE', 'Base Fare'), ('DISTANCE_FARE', 'Distance'), ('DURATION_FARE', 'Duration'), ('WAITING_FARE', 'Waiting Time'), ('SURGE_ADJUSTMENT', 'Surge'), ('TOLLS', 'Tolls'), ('MINIMUM_FARE_ADJUSTMENT', 'Minimum Fare Adjustment'), ('TAX', 'Tax'), ('DISCOUNT', 'Discount'), ('CANCELLATION_FEE', 'Cancellation Fee')], max_length=30)),
                ('label', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sequence', models.PositiveSmallIntegerField()),
                ('fare', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='pricing.fare')),
            ],
            options={
                'db_table': 'pricing_fare_line_item',
                'ordering': ['fare', 'sequence'],
            },
        ),
        migrations.CreateModel(
            name='PricingRule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('base_fare', models.DecimalField(decimal_places=2, max_digits=8)),
                ('per_km_rate', models.DecimalField(decimal_places=2, max_digits=8)),
                ('per_minute_rate', models.DecimalField(decimal_places=2, max_digits=8)),
                ('per_minute_waiting_rate', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('minimum_fare', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cancellation_fee', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('surge_multiplier', models.DecimalField(decimal_places=2, default=1, max_digits=4)),
                ('tax_rate', models.DecimalField(decimal_places=4, default=0, help_text='Fraction, e.g. 0.15 for 15%.', max_digits=5)),
                ('vehicle_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_rule', to='vehicles.vehicletype')),
            ],
            options={
                'db_table': 'pricing_rule',
                'ordering': ['vehicle_type__name'],
            },
        ),
        migrations.AddConstraint(
            model_name='fare',
            constraint=models.UniqueConstraint(fields=('ride', 'fare_type'), name='uniq_fare_per_ride_and_type'),
        ),
    ]
