# Generated by Django 6.1.1 on 2026-09-19 12:08

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rides', '0002_ride_estimated_distance_km_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('direction', models.CharField(choices=[('RIDER_TO_DRIVER', 'Rider rates Driver'), ('DRIVER_TO_RIDER', 'Driver rates Rider')], max_length=20)),
                ('score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('review', models.CharField(blank=True, max_length=1000)),
                ('ratee', models.ForeignKey(blank=True, help_text='Null when rating a guest rider, who has no account.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratings_received', to=settings.AUTH_USER_MODEL)),
                ('rater', models.ForeignKey(blank=True, help_text='Null when a guest rider submitted the rating (no account to attribute it to).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ratings_given', to=settings.AUTH_USER_MODEL)),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ratings', to='rides.ride')),
            ],
            options={
                'db_table': 'ratings_rating',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['ratee', 'direction'], name='ratings_rat_ratee_i_ecf4f1_idx')],
                'constraints': [models.UniqueConstraint(fields=('ride', 'direction'), name='uniq_rating_per_ride_direction')],
            },
        ),
    ]
