# Generated by Django 6.1.1 on 2026-09-07 03:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0002_driver_average_rating_driver_is_available_and_more'),
        ('rides', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DispatchOffer',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('EXPIRED', 'Expired'), ('SUPERSEDED', 'Superseded')], db_index=True, default='PENDING', max_length=20)),
                ('distance_km', models.DecimalField(decimal_places=3, max_digits=6)),
                ('expires_at', models.DateTimeField()),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatch_offers', to='drivers.driver')),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatch_offers', to='rides.ride')),
            ],
            options={
                'db_table': 'dispatch_offer',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['ride', 'status'], name='dispatch_of_ride_id_96dae2_idx')],
                'constraints': [models.UniqueConstraint(fields=('ride', 'driver'), name='uniq_dispatch_offer_per_ride_driver')],
            },
        ),
    ]
