# Generated by Django 6.1.1 on 2026-09-06 21:27

import apps.rides.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0001_initial'),
        ('vehicles', '0002_seed_vehicle_types'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('guest_phone_number', models.CharField(blank=True, db_index=True, max_length=32, null=True)),
                ('guest_name', models.CharField(blank=True, max_length=150)),
                ('tracking_token', models.UUIDField(db_index=True, default=apps.rides.models._generate_tracking_token, editable=False, unique=True)),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('SEARCHING_DRIVER', 'Searching for Driver'), ('DRIVER_ASSIGNED', 'Driver Assigned'), ('DRIVER_ACCEPTED', 'Driver Accepted'), ('DRIVER_ARRIVING', 'Driver Arriving'), ('DRIVER_ARRIVED', 'Driver Arrived'), ('TRIP_STARTED', 'Trip Started'), ('TRIP_COMPLETED', 'Trip Completed'), ('PAYMENT_PENDING', 'Payment Pending'), ('PAID', 'Paid'), ('RATED', 'Rated'), ('CANCELLED_BY_RIDER', 'Cancelled by Rider'), ('CANCELLED_BY_DRIVER', 'Cancelled by Driver'), ('EXPIRED', 'Expired'), ('NO_DRIVER_FOUND', 'No Driver Found')], db_index=True, default='REQUESTED', max_length=20)),
                ('version', models.PositiveIntegerField(default=0)),
                ('pickup_address', models.CharField(max_length=255)),
                ('pickup_latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('pickup_longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('destination_address', models.CharField(max_length=255)),
                ('destination_latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('destination_longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('driver_assigned_at', models.DateTimeField(blank=True, null=True)),
                ('driver_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('trip_started_at', models.DateTimeField(blank=True, null=True)),
                ('trip_completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.CharField(blank=True, max_length=255)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rides_as_driver', to='drivers.driver')),
                ('rider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rides_as_rider', to=settings.AUTH_USER_MODEL)),
                ('vehicle_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rides', to='vehicles.vehicletype')),
            ],
            options={
                'db_table': 'rides_ride',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RideStatusHistory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_status', models.CharField(blank=True, max_length=20)),
                ('to_status', models.CharField(max_length=20)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('changed_by', models.ForeignKey(blank=True, help_text='Null for system-triggered transitions or guest-initiated actions.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ride_status_changes', to=settings.AUTH_USER_MODEL)),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='rides.ride')),
            ],
            options={
                'db_table': 'rides_ride_status_history',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='ride',
            index=models.Index(fields=['status', 'created_at'], name='rides_ride_status_9f4eb8_idx'),
        ),
        migrations.AddConstraint(
            model_name='ride',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('guest_phone_number__isnull', True), ('rider__isnull', False)), models.Q(('guest_phone_number__isnull', False), ('rider__isnull', True)), _connector='OR'), name='ride_exactly_one_of_rider_or_guest_phone'),
        ),
    ]
