# Generated by Django 6.1.1 on 2026-09-07 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='average_rating',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Populated once Ratings (Phase 11) exists. Null is treated as neutral in ranking.', max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='is_available',
            field=models.BooleanField(db_index=True, default=False, help_text='Online/offline toggle, set by the driver.'),
        ),
        migrations.AddField(
            model_name='driver',
            name='total_offers_accepted',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='driver',
            name='total_offers_sent',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
