# Generated by Django 6.1.1 on 2026-09-19 12:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_email', models.CharField(blank=True, help_text='Snapshotted at write time, so the entry stays readable if the account goes away.', max_length=254)),
                ('action', models.CharField(choices=[('DRIVER_APPROVED', 'Driver Approved'), ('DRIVER_REJECTED', 'Driver Rejected'), ('DRIVER_SUSPENDED', 'Driver Suspended'), ('DRIVER_REACTIVATED', 'Driver Reactivated'), ('PRICING_RULE_UPDATED', 'Pricing Rule Updated'), ('PAYMENT_REFUNDED', 'Payment Refunded'), ('PAYOUT_COMPLETED', 'Payout Completed'), ('PAYOUT_FAILED', 'Payout Failed'), ('RIDE_DRIVER_ASSIGNED', 'Ride Driver Manually Assigned'), ('USER_SUSPENDED', 'User Suspended')], db_index=True, max_length=40)),
                ('target_type', models.CharField(help_text="e.g. 'Driver', 'PricingRule', 'Payment'.", max_length=50)),
                ('target_id', models.CharField(max_length=64)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, help_text='Null if the acting account was later deleted — the entry itself still stands.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'admin_api_audit_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['target_type', 'target_id'], name='admin_api_a_target__58f1e4_idx'), models.Index(fields=['actor', 'created_at'], name='admin_api_a_actor_i_672445_idx')],
            },
        ),
    ]
