# Generated by Django 6.1.1 on 2026-09-07 19:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0002_driver_average_rating_driver_is_available_and_more'),
        ('rides', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverLocation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('heading', models.DecimalField(blank=True, decimal_places=2, help_text='Compass heading, 0-360 degrees.', max_digits=5, null=True)),
                ('speed', models.DecimalField(blank=True, decimal_places=2, help_text='km/h.', max_digits=6, null=True)),
                ('accuracy', models.DecimalField(blank=True, decimal_places=2, help_text='meters.', max_digits=6, null=True)),
                ('recorded_at', models.DateTimeField(help_text='Client-reported timestamp of this position.')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_history', to='drivers.driver')),
                ('ride', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_history', to='rides.ride')),
            ],
            options={
                'db_table': 'locations_driver_location',
                'ordering': ['recorded_at'],
                'indexes': [models.Index(fields=['ride', 'recorded_at'], name='locations_d_ride_id_f455e9_idx'), models.Index(fields=['driver', 'recorded_at'], name='locations_d_driver__af00a8_idx')],
            },
        ),
    ]
