# Generated by Django 6.1.1 on 2026-09-10 04:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pricing', '0002_seed_pricing_rules'),
        ('rides', '0002_ride_estimated_distance_km_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('method', models.CharField(choices=[('CASH', 'Cash'), ('CARD', 'Card'), ('MOBILE_MONEY', 'Mobile Money')], max_length=20)),
                ('provider_name', models.CharField(blank=True, help_text="Empty for CASH; e.g. 'stripe' or 'chapa' otherwise.", max_length=30)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('AUTHORIZED', 'Authorized'), ('CAPTURED', 'Captured'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded'), ('PARTIALLY_REFUNDED', 'Partially Refunded')], default='PENDING', max_length=20)),
                ('currency', models.CharField(max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('provider_reference', models.CharField(blank=True, db_index=True, help_text="The provider's own id for this charge.", max_length=255)),
                ('idempotency_key', models.CharField(max_length=64, unique=True)),
                ('failure_reason', models.CharField(blank=True, max_length=255)),
                ('fare', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payment', to='pricing.fare')),
                ('ride', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payment', to='rides.ride')),
            ],
            options={
                'db_table': 'payments_payment',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('AUTHORIZATION', 'Authorization'), ('CAPTURE', 'Capture'), ('REFUND', 'Refund'), ('FAILURE', 'Failure')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('provider_reference', models.CharField(blank=True, max_length=255)),
                ('idempotency_key', models.CharField(max_length=128, unique=True)),
                ('raw_response', models.JSONField(blank=True, help_text="The provider's raw response/event, for audit.", null=True)),
                ('initiated_by', models.ForeignKey(blank=True, help_text='Null for provider-webhook-driven transactions.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_transactions_initiated', to=settings.AUTH_USER_MODEL)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='payments.payment')),
            ],
            options={
                'db_table': 'payments_payment_transaction',
                'ordering': ['created_at'],
            },
        ),
    ]
